/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import { UnsignedTransaction } from "ethers/utils/transaction";
import { TypedEventDescription, TypedFunctionDescription } from ".";

interface IERC165Interface extends Interface {
  functions: {
    supportsInterface: TypedFunctionDescription<{
      encode([interfaceId]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class IERC165 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IERC165;
  attach(addressOrName: string): IERC165;
  deployed(): Promise<IERC165>;

  on(event: EventFilter | string, listener: Listener): IERC165;
  once(event: EventFilter | string, listener: Listener): IERC165;
  addListener(eventName: EventFilter | string, listener: Listener): IERC165;
  removeAllListeners(eventName: EventFilter | string): IERC165;
  removeListener(eventName: any, listener: Listener): IERC165;

  interface: IERC165Interface;

  functions: {
    supportsInterface(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<boolean>;
  };

  supportsInterface(
    interfaceId: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: Arrayish,
    overrides?: UnsignedTransaction
  ): Promise<boolean>;

  filters: {};

  estimate: {
    supportsInterface(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: Arrayish,
      overrides?: UnsignedTransaction
    ): Promise<BigNumber>;
  };
}
